/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as ResetPasswordRouteImport } from './routes/resetPassword'
import { Route as RecentsRouteImport } from './routes/recents'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordResettokenRouteImport } from './routes/reset-password.$resettoken'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentsRoute = RecentsRouteImport.update({
  id: '/recents',
  path: '/recents',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordResettokenRoute = ResetPasswordResettokenRouteImport.update({
  id: '/reset-password/$resettoken',
  path: '/reset-password/$resettoken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/images': typeof ImagesRoute
  '/recents': typeof RecentsRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/upload': typeof UploadRoute
  '/reset-password/$resettoken': typeof ResetPasswordResettokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/images': typeof ImagesRoute
  '/recents': typeof RecentsRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/upload': typeof UploadRoute
  '/reset-password/$resettoken': typeof ResetPasswordResettokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/images': typeof ImagesRoute
  '/recents': typeof RecentsRoute
  '/resetPassword': typeof ResetPasswordRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/upload': typeof UploadRoute
  '/reset-password/$resettoken': typeof ResetPasswordResettokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/images'
    | '/recents'
    | '/resetPassword'
    | '/signIn'
    | '/signUp'
    | '/upload'
    | '/reset-password/$resettoken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/images'
    | '/recents'
    | '/resetPassword'
    | '/signIn'
    | '/signUp'
    | '/upload'
    | '/reset-password/$resettoken'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/images'
    | '/recents'
    | '/resetPassword'
    | '/signIn'
    | '/signUp'
    | '/upload'
    | '/reset-password/$resettoken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  ImagesRoute: typeof ImagesRoute
  RecentsRoute: typeof RecentsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UploadRoute: typeof UploadRoute
  ResetPasswordResettokenRoute: typeof ResetPasswordResettokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recents': {
      id: '/recents'
      path: '/recents'
      fullPath: '/recents'
      preLoaderRoute: typeof RecentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$resettoken': {
      id: '/reset-password/$resettoken'
      path: '/reset-password/$resettoken'
      fullPath: '/reset-password/$resettoken'
      preLoaderRoute: typeof ResetPasswordResettokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  ImagesRoute: ImagesRoute,
  RecentsRoute: RecentsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UploadRoute: UploadRoute,
  ResetPasswordResettokenRoute: ResetPasswordResettokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
